touch-drivers:xiaomi: Export symbols for ft3418_i2c
* ft3418_i2c needs to access xiaomitouch_register_modedata and get_xiaomi_touch_class from xiaomi touch.
* EXPORT_SYMBOL need for it when xiaomi touch compiled as module.

else

ERROR: modpost: "xiaomitouch_register_modedata" [../../vendor/qcom/opensource/touch-drivers/focaltech_fts_i2c.ko] undefined!
ERROR: modpost: "get_xiaomi_touch_class" [../../vendor/qcom/opensource/touch-drivers/focaltech_fts_i2c.ko] undefined!

Signed-off-by: muralivijay <muralidharan9845@gmail.com>